"""
Hardware model and vendor mapping for Meshtastic devices.
Based on https://github.com/meshtastic/firmware/tree/master/src/mesh/generated/meshtastic/mesh.pb.h
"""

# Hardware model ID to human-readable name mapping
HARDWARE_MODELS = {
    0: "UNSET",
    1: "TLORA V2",
    2: "TLORA V1",
    3: "TLORA V2.1 1.6",
    4: "T-Beam",
    5: "Heltec V2.0",
    6: "T-Beam V0.7",
    7: "T-Echo",
    8: "TLORA V1.3",
    9: "RAK4631",
    10: "Heltec V2.1",
    11: "Heltec V1",
    12: "T-Beam S3 Core",
    13: "RAK11200",
    14: "Nano G1",
    15: "TLORA V2.1 1.8",
    16: "TLORA T3 S3",
    17: "Nano G1 Explorer",
    18: "Nano G2 Ultra",
    19: "LoRa Type",
    20: "WiPhone",
    21: "WIO WM1110",
    22: "RAK2560",
    23: "Heltec HRU-3601",
    24: "Heltec Wireless Bridge",
    25: "Station G1",
    26: "RAK11310",
    27: "SenseLoRA RP2040",
    28: "SenseLoRA S3",
    29: "CanaryOne",
    30: "RP2040 LoRa",
    31: "Station G2",
    32: "LoRa Relay V1",
    33: "nRF52840DK",
    34: "PPR",
    35: "GenieBlocks",
    36: "nRF52 Unknown",
    37: "Portduino",
    38: "Android Sim",
    39: "DIY V1",
    40: "nRF52840 PCA10059",
    41: "DR Dev",
    42: "M5Stack",
    43: "Heltec V3",
    44: "Heltec WSL V3",
    45: "BetaFPV 2400 TX",
    46: "BetaFPV 900 Nano TX",
    47: "RPI Pico",
    48: "Heltec Wireless Tracker",
    49: "Heltec Wireless Paper",
    50: "T-Deck",
    51: "T-Watch S3",
    52: "Picomputer S3",
    53: "Heltec HT62",
    54: "Ebyte ESP32 S3",
    55: "ESP32 S3 Pico",
    56: "Chatter 2",
    57: "Heltec Wireless Paper V1.0",
    58: "Heltec Wireless Tracker V1.0",
    59: "unPhone",
    60: "TD LoRaC",
    61: "CDebyte EoRa S3",
    62: "TWC Mesh V4",
    63: "nRF52 ProMicro DIY",
    64: "RadioMaster 900 Bandit Nano",
    65: "Heltec Capsule Sensor V3",
    66: "Heltec Vision Master T190",
    67: "Heltec Vision Master E213",
    68: "Heltec Vision Master E290",
    69: "Heltec Mesh Node T114",
    70: "SenseCap Indicator",
    71: "Tracker T1000-E",
    72: "RAK3172",
    73: "WIO E5",
    74: "RadioMaster 900 Bandit",
    75: "ME25LS01 4Y10TD",
    76: "RP2040 Feather RFM95",
    77: "M5Stack Core Basic",
    78: "M5Stack Core2",
    79: "RPI Pico2",
    80: "M5Stack CoreS3",
    81: "Seeed XIAO S3",
    82: "MS24SF1",
    83: "TLora C6",
    84: "WisMesh Tap",
    85: "Routastic",
    86: "Mesh Tab",
    87: "MeshLink",
    88: "XIAO nRF52 Kit",
    89: "ThinkNode M1",
    90: "ThinkNode M2",
    91: "T-ETH Elite",
    92: "Heltec Sensor Hub",
    93: "Reserved Fried Chicken",
    94: "Heltec Mesh Pocket",
    95: "Seeed Solar Node",
    96: "NomadStar Meteor Pro",
    97: "CrowPanel",
    98: "Link 32",
    99: "Seeed Wio Tracker L1",
    100: "Seeed Wio Tracker L1 E-Ink",
    101: "Qwantz Tiny Arms",
    102: "T-Deck Pro",
    103: "T-LoRa Pager",
    104: "GAT562 Mesh Trial Tracker",
    255: "Private Hardware"
}

# Hardware vendor mapping based on model names and known manufacturers
HARDWARE_VENDORS = {
    0: "Unknown",
    1: "LilyGO",
    2: "LilyGO", 
    3: "LilyGO",
    4: "LilyGO",
    5: "Heltec",
    6: "LilyGO",
    7: "LilyGO",
    8: "LilyGO",
    9: "RAK Wireless",
    10: "Heltec",
    11: "Heltec",
    12: "LilyGO",
    13: "RAK Wireless",
    14: "B&Q Consulting",
    15: "LilyGO",
    16: "LilyGO",
    17: "B&Q Consulting",
    18: "B&Q Consulting",
    19: "LoRaType",
    20: "WiPhone",
    21: "Seeed Studio",
    22: "RAK Wireless",
    23: "Heltec",
    24: "Heltec",
    25: "B&Q Consulting",
    26: "RAK Wireless",
    27: "Makerfabs",
    28: "Makerfabs",
    29: "Canary Radio",
    30: "Waveshare",
    31: "B&Q Consulting",
    32: "Unknown",
    33: "Nordic",
    34: "Unknown",
    35: "GenieBlocks",
    36: "Nordic",
    37: "Linux",
    38: "Android",
    39: "DIY",
    40: "Nordic",
    41: "Disaster Radio",
    42: "M5Stack",
    43: "Heltec",
    44: "Heltec",
    45: "BetaFPV",
    46: "BetaFPV",
    47: "Raspberry Pi",
    48: "Heltec",
    49: "Heltec",
    50: "LilyGO",
    51: "LilyGO",
    52: "Bobricius",
    53: "Heltec",
    54: "Ebyte",
    55: "Waveshare",
    56: "CircuitMess",
    57: "Heltec",
    58: "Heltec",
    59: "unPhone",
    60: "Teledatics",
    61: "CDebyte",
    62: "TWC",
    63: "DIY",
    64: "RadioMaster",
    65: "Heltec",
    66: "Heltec",
    67: "Heltec",
    68: "Heltec",
    69: "Heltec",
    70: "Seeed Studio",
    71: "Seeed Studio",
    72: "RAK Wireless",
    73: "Seeed Studio",
    74: "RadioMaster",
    75: "Minewsemi",
    76: "Adafruit",
    77: "M5Stack",
    78: "M5Stack",
    79: "Raspberry Pi",
    80: "M5Stack",
    81: "Seeed Studio",
    82: "Unknown",
    83: "LilyGO",
    84: "RAK Wireless",
    85: "Routastic",
    86: "Mesh Tab",
    87: "LoraItalia",
    88: "Seeed Studio",
    89: "Elecrow",
    90: "Elecrow",
    91: "LilyGO",
    92: "Heltec",
    93: "Reserved",
    94: "Heltec",
    95: "Seeed Studio",
    96: "NomadStar",
    97: "Elecrow",
    98: "LilyGO",
    99: "Seeed Studio",
    100: "Seeed Studio",
    101: "Reserved",
    102: "LilyGO",
    103: "LilyGO",
    104: "GAT562",
    255: "Private"
}

def get_hardware_info(hw_model_id):
    """
    Get hardware model name and vendor for a given hardware model ID.
    
    Args:
        hw_model_id (int): The hardware model ID
        
    Returns:
        dict: Dictionary with 'model_name' and 'vendor' keys
    """
    if hw_model_id is None:
        return {"model_name": "Unknown", "vendor": "Unknown"}
    
    hardware_model_name = HARDWARE_MODELS.get(hw_model_id, f"Unknown Model {hw_model_id}")
    hardware_vendor = HARDWARE_VENDORS.get(hw_model_id, "Unknown")
    
    return {"model_name": hardware_model_name, "vendor": hardware_vendor}

def get_hardware_model_name(hw_model_id):
    """Get the hardware model name for a given ID."""
    return HARDWARE_MODELS.get(hw_model_id, f"Unknown Model {hw_model_id}")

def get_hardware_vendor(hw_model_id):
    """Get the hardware vendor for a given ID."""
    return HARDWARE_VENDORS.get(hw_model_id, "Unknown")
